id: d7_adsense_settings
label: AdSense 7 configuration
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - adsense_visibility
    - adsense_access_pages
    - adsense_unblock_ads
    - adsense_test_mode
    - adsense_disable
    - adsense_placeholder
    - adsense_placeholder_text
    - adsense_secret_language
    - adsense_basic_id
    - adsense_id_module
    - adsense_managed_async
    - adsense_managed_page_level_ads_enabled
    - adsense_cse_logo
    - adsense_cse_color_box_background
    - adsense_cse_encoding
    - adsense_cse_textbox_length
    - adsense_cse_language
    - adsense_cse_country
    - adsense_cse_frame_width
    - adsense_cse_ad_location
  source_module: adsense
process:
  adsense_unblock_ads: adsense_unblock_ads
  adsense_test_mode: adsense_test_mode
  adsense_disable: adsense_disable
  adsense_placeholder: adsense_placeholder
  adsense_placeholder_text: adsense_placeholder_text
  adsense_secret_language: adsense_secret_language
  adsense_managed_page_level_ads_enabled: adsense_managed_page_level_ads_enabled
  'adsense_access_pages/id': 'request_path'
  'adsense_access_pages/pages': adsense_access_pages
  'adsense_access_pages/negate': adsense_visibility
  adsense_basic_id: adsense_basic_id
  adsense_id_module: adsense_id_module
  adsense_managed_async: adsense_managed_async
  adsense_cse_logo: adsense_cse_logo
  adsense_cse_color_box_background: adsense_cse_color_box_background
  adsense_cse_encoding: adsense_cse_encoding
  adsense_cse_textbox_length: adsense_cse_textbox_length
  adsense_cse_language: adsense_cse_language
  adsense_cse_country: adsense_cse_country
  adsense_cse_frame_width: adsense_cse_frame_width
  adsense_cse_ad_location: adsense_cse_ad_location
destination:
  plugin: config
  config_name: adsense.settings
