adsense_oldcode.settings:
  type: config_object
  label: 'AdSense pre-2007 code Settings'
  mapping:
    adsense_group_title_1:
      type: string
      label: 'Title of the style'
    adsense_ad_type_1:
      type: integer
      label: 'Ad type'
    adsense_color_text_1:
      type: string
      label: 'Text color'
    adsense_color_border_1:
      type: string
      label: 'Border color'
    adsense_color_bg_1:
      type: string
      label: 'Background color'
    adsense_color_link_1:
      type: string
      label: 'Title color'
    adsense_color_url_1:
      type: string
      label: 'URL color'
    adsense_alt_1:
      type: integer
      label: 'Alternate URL color'
    adsense_alt_info_1:
      type: string
      label: 'Alternate info'
    adsense_ui_features_1:
      type: string
      label: 'Rounded corners'
    adsense_group_title_2:
      type: string
      label: 'Title of the style'
    adsense_ad_type_2:
      type: integer
      label: 'Ad type'
    adsense_color_text_2:
      type: string
      label: 'Text color'
    adsense_color_border_2:
      type: string
      label: 'Border color'
    adsense_color_bg_2:
      type: string
      label: 'Background color'
    adsense_color_link_2:
      type: string
      label: 'Title color'
    adsense_color_url_2:
      type: string
      label: 'URL color'
    adsense_alt_2:
      type: integer
      label: 'Alternate URL color'
    adsense_alt_info_2:
      type: string
      label: 'Alternate info'
    adsense_ui_features_2:
      type: string
      label: 'Rounded corners'
    adsense_group_title_3:
      type: string
      label: 'Title of the style'
    adsense_ad_type_3:
      type: integer
      label: 'Ad type'
    adsense_color_text_3:
      type: string
      label: 'Text color'
    adsense_color_border_3:
      type: string
      label: 'Border color'
    adsense_color_bg_3:
      type: string
      label: 'Background color'
    adsense_color_link_3:
      type: string
      label: 'Title color'
    adsense_color_url_3:
      type: string
      label: 'URL color'
    adsense_alt_3:
      type: integer
      label: 'Alternate URL color'
    adsense_alt_info_3:
      type: string
      label: 'Alternate info'
    adsense_ui_features_3:
      type: string
      label: 'Rounded corners'
    adsense_group_title_4:
      type: string
      label: 'Title of the style'
    adsense_ad_type_4:
      type: integer
      label: 'Ad type'
    adsense_color_text_4:
      type: string
      label: 'Text color'
    adsense_color_border_4:
      type: string
      label: 'Border color'
    adsense_color_bg_4:
      type: string
      label: 'Background color'
    adsense_color_link_4:
      type: string
      label: 'Title color'
    adsense_color_url_4:
      type: string
      label: 'URL color'
    adsense_alt_4:
      type: integer
      label: 'Alternate URL color'
    adsense_alt_info_4:
      type: string
      label: 'Alternate info'
    adsense_ui_features_4:
      type: string
      label: 'Rounded corners'
    adsense_group_title_5:
      type: string
      label: 'Title of the style'
    adsense_ad_type_5:
      type: integer
      label: 'Ad type'
    adsense_color_text_5:
      type: string
      label: 'Text color'
    adsense_color_border_5:
      type: string
      label: 'Border color'
    adsense_color_bg_5:
      type: string
      label: 'Background color'
    adsense_color_link_5:
      type: string
      label: 'Title color'
    adsense_color_url_5:
      type: string
      label: 'URL color'
    adsense_alt_5:
      type: integer
      label: 'Alternate URL color'
    adsense_alt_info_5:
      type: string
      label: 'Alternate info'
    adsense_ui_features_5:
      type: string
      label: 'Rounded corners'
    adsense_search_button:
      type: boolean
      label: 'Search button below text box'
    adsense_search_color_bg:
      type: string
      label: 'Background'
    adsense_search_color_border:
      type: string
      label: 'Border'
    adsense_search_color_box_background:
      type: string
      label: 'Background color'
    adsense_search_color_box_text:
      type: string
      label: 'Text color'
    adsense_search_color_light_url:
      type: string
      label: 'Light URL'
    adsense_search_color_logo_bg:
      type: string
      label: 'Logo Background'
    adsense_search_color_text:
      type: string
      label: 'Text'
    adsense_search_color_title:
      type: string
      label: 'Title'
    adsense_search_color_url:
      type: string
      label: 'URL'
    adsense_search_color_visited_url:
      type: string
      label: 'Visited URL'
    adsense_search_country:
      type: string
      label: 'Country or territory for Google domain'
    adsense_search_domain_0:
      type: string
      label: 'Specific search domain 1'
    adsense_search_domain_1:
      type: string
      label: 'Specific search domain 2'
    adsense_search_domain_2:
      type: string
      label: 'Specific search domain 3'
    adsense_search_encoding:
      type: string
      label: 'Site Encoding'
    adsense_search_frame_width:
      type: integer
      label: 'Width of results area'
    adsense_search_language:
      type: string
      label: 'Site Language'
    adsense_search_logo:
      type: string
      label: 'Logo Type'
    adsense_search_safe_mode:
      type: boolean
      label: 'Use SafeSearch'
    adsense_search_textbox_length:
      type: integer
      label: 'Length of text box'

block.settings.adsense_oldcode_ad_block:
  type: block_settings
  label: 'Managed ad block settings'
  mapping:
    ad_format:
      type: string
      label: 'Ad format'
    ad_style:
      type: string
      label: 'Style'
    ad_channel:
      type: string
      label: 'Channel'
    ad_align:
      type: string
      label: 'Ad alignment'

block.settings.adsense_oldsearch_ad_block:
  type: block_settings
  label: 'Custom search block settings'
  mapping:
    ad_channel:
      type: string
      label: 'Channel'
