adsense.settings:
  type: config_object
  label: 'AdSense Settings'
  mapping:
    adsense_unblock_ads:
      type: boolean
      label: 'Display anti ad-block request'
    adsense_test_mode:
      type: boolean
      label: 'Enable test mode'
    adsense_disable:
      type: boolean
      label: 'Disable Google AdSense ads'
    adsense_placeholder:
      type: boolean
      label: 'Placeholder when ads are disabled'
    adsense_placeholder_text:
      type: string
      label: 'Placeholder text'
    adsense_secret_language:
      type: string
      label: 'Language to display ads'
    adsense_managed_page_level_ads_enabled:
      type: boolean
      label: 'Enable auto ads'
    adsense_access_pages:
      type: mapping
      label: 'Access pages'
      mapping:
        id:
          type: string
          label: 'PlugIn ID'
        pages:
          type: string
          label: 'Access pages'
        negate:
          type: string
          label: 'Hide for the listed pages'
    adsense_basic_id:
      type: string
      label: 'Site Google AdSense publisher ID'
    adsense_id_module:
      type: string
      label: 'Publisher ID module'
    adsense_managed_async:
      type: boolean
      label: 'Use asynchronous code'
    adsense_managed_defer:
      type: boolean
      label: 'Defer script execution'
    adsense_cse_logo:
      type: string
      label: 'Logo type'
    adsense_cse_color_box_background:
      type: string
      label: 'Background color'
    adsense_cse_encoding:
      type: string
      label: 'Site encoding'
    adsense_cse_textbox_length:
      type: integer
      label: 'Text box length'
    adsense_cse_language:
      type: string
      label: 'Watermark language'
    adsense_cse_country:
      type: string
      label: 'Country or territory for Google domain'
    adsense_cse_frame_width:
      type: integer
      label: 'Width of results area'
    adsense_cse_ad_location:
      type: string
      label: 'Ad location'

block.settings.adsense_cse_ad_block:
  type: block_settings
  label: 'Custom search block settings'
  mapping:
    ad_slot:
      type: string
      label: 'Ad ID'

block.settings.adsense_managed_ad_block:
  type: block_settings
  label: 'Managed ad block settings'
  mapping:
    ad_slot:
      type: string
      label: 'Ad ID'
    ad_format:
      type: string
      label: 'Ad format'
    ad_width:
      type: integer
      label: 'Width'
    ad_height:
      type: integer
      label: 'Height'
    ad_shape:
      type: sequence
      label: 'Responsive ad shape'
      sequence:
        type: string
    ad_align:
      type: string
      label: 'Ad alignment'
