id: d7_adsense_oldcode_settings
label: AdSense pre-2007 code 7 configuration
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - adsense_ad_channel_1
    - adsense_ad_channel_2
    - adsense_ad_channel_3
    - adsense_ad_channel_4
    - adsense_ad_channel_5
    - adsense_ad_channel_6
    - adsense_ad_channel_7
    - adsense_ad_channel_8
    - adsense_ad_channel_9
    - adsense_ad_channel_10
    - adsense_group_title_1
    - adsense_ad_type_1
    - adsense_color_text_1
    - adsense_color_border_1
    - adsense_color_bg_1
    - adsense_color_link_1
    - adsense_color_url_1
    - adsense_alt_1
    - adsense_alt_info_1
    - adsense_ui_features_1
    - adsense_group_title_2
    - adsense_ad_type_2
    - adsense_color_text_2
    - adsense_color_border_2
    - adsense_color_bg_2
    - adsense_color_link_2
    - adsense_color_url_2
    - adsense_alt_2
    - adsense_alt_info_2
    - adsense_ui_features_2
    - adsense_group_title_3
    - adsense_ad_type_3
    - adsense_color_text_3
    - adsense_color_border_3
    - adsense_color_bg_3
    - adsense_color_link_3
    - adsense_color_url_3
    - adsense_alt_3
    - adsense_alt_info_3
    - adsense_ui_features_3
    - adsense_group_title_4
    - adsense_ad_type_4
    - adsense_color_text_4
    - adsense_color_border_4
    - adsense_color_bg_4
    - adsense_color_link_4
    - adsense_color_url_4
    - adsense_alt_4
    - adsense_alt_info_4
    - adsense_ui_features_4
    - adsense_group_title_5
    - adsense_ad_type_5
    - adsense_color_text_5
    - adsense_color_border_5
    - adsense_color_bg_5
    - adsense_color_link_5
    - adsense_color_url_5
    - adsense_alt_5
    - adsense_alt_info_5
    - adsense_ui_features_5
    - adsense_search_button
    - adsense_search_color_bg
    - adsense_search_color_border
    - adsense_search_color_box_background
    - adsense_search_color_box_text
    - adsense_search_color_light_url
    - adsense_search_color_logo_bg
    - adsense_search_color_text
    - adsense_search_color_title
    - adsense_search_color_url
    - adsense_search_color_visited_url
    - adsense_search_country
    - adsense_search_domain_0
    - adsense_search_domain_1
    - adsense_search_domain_2
    - adsense_search_encoding
    - adsense_search_frame_width
    - adsense_search_language
    - adsense_search_logo
    - adsense_search_safe_mode
    - adsense_search_textbox_length
  source_module: adsense_oldcode
process:
    adsense_ad_channel_1: adsense_ad_channel_1
    adsense_ad_channel_2: adsense_ad_channel_2
    adsense_ad_channel_3: adsense_ad_channel_3
    adsense_ad_channel_4: adsense_ad_channel_4
    adsense_ad_channel_5: adsense_ad_channel_5
    adsense_ad_channel_6: adsense_ad_channel_6
    adsense_ad_channel_7: adsense_ad_channel_7
    adsense_ad_channel_8: adsense_ad_channel_8
    adsense_ad_channel_9: adsense_ad_channel_9
    adsense_ad_channel_10: adsense_ad_channel_10
    adsense_group_title_1: adsense_group_title_1
    adsense_ad_type_1: adsense_ad_type_1
    adsense_color_text_1: adsense_color_text_1
    adsense_color_border_1: adsense_color_border_1
    adsense_color_bg_1: adsense_color_bg_1
    adsense_color_link_1: adsense_color_link_1
    adsense_color_url_1: adsense_color_url_1
    adsense_alt_1: adsense_alt_1
    adsense_alt_info_1: adsense_alt_info_1
    adsense_ui_features_1: adsense_ui_features_1
    adsense_group_title_2: adsense_group_title_2
    adsense_ad_type_2: adsense_ad_type_2
    adsense_color_text_2: adsense_color_text_2
    adsense_color_border_2: adsense_color_border_2
    adsense_color_bg_2: adsense_color_bg_2
    adsense_color_link_2: adsense_color_link_2
    adsense_color_url_2: adsense_color_url_2
    adsense_alt_2: adsense_alt_2
    adsense_alt_info_2: adsense_alt_info_2
    adsense_ui_features_2: adsense_ui_features_2
    adsense_group_title_3: adsense_group_title_3
    adsense_ad_type_3: adsense_ad_type_3
    adsense_color_text_3: adsense_color_text_3
    adsense_color_border_3: adsense_color_border_3
    adsense_color_bg_3: adsense_color_bg_3
    adsense_color_link_3: adsense_color_link_3
    adsense_color_url_3: adsense_color_url_3
    adsense_alt_3: adsense_alt_3
    adsense_alt_info_3: adsense_alt_info_3
    adsense_ui_features_3: adsense_ui_features_3
    adsense_group_title_4: adsense_group_title_4
    adsense_ad_type_4: adsense_ad_type_4
    adsense_color_text_4: adsense_color_text_4
    adsense_color_border_4: adsense_color_border_4
    adsense_color_bg_4: adsense_color_bg_4
    adsense_color_link_4: adsense_color_link_4
    adsense_color_url_4: adsense_color_url_4
    adsense_alt_4: adsense_alt_4
    adsense_alt_info_4: adsense_alt_info_4
    adsense_ui_features_4: adsense_ui_features_4
    adsense_group_title_5: adsense_group_title_5
    adsense_ad_type_5: adsense_ad_type_5
    adsense_color_text_5: adsense_color_text_5
    adsense_color_border_5: adsense_color_border_5
    adsense_color_bg_5: adsense_color_bg_5
    adsense_color_link_5: adsense_color_link_5
    adsense_color_url_5: adsense_color_url_5
    adsense_alt_5: adsense_alt_5
    adsense_alt_info_5: adsense_alt_info_5
    adsense_ui_features_5: adsense_ui_features_5
    adsense_search_button: adsense_search_button
    adsense_search_color_bg: adsense_search_color_bg
    adsense_search_color_border: adsense_search_color_border
    adsense_search_color_box_background: adsense_search_color_box_background
    adsense_search_color_box_text: adsense_search_color_box_text
    adsense_search_color_light_url: adsense_search_color_light_url
    adsense_search_color_logo_bg: adsense_search_color_logo_bg
    adsense_search_color_text: adsense_search_color_text
    adsense_search_color_title: adsense_search_color_title
    adsense_search_color_url: adsense_search_color_url
    adsense_search_color_visited_url: adsense_search_color_visited_url
    adsense_search_country: adsense_search_country
    adsense_search_domain_0: adsense_search_domain_0
    adsense_search_domain_1: adsense_search_domain_1
    adsense_search_domain_2: adsense_search_domain_2
    adsense_search_encoding: adsense_search_encoding
    adsense_search_frame_width: adsense_search_frame_width
    adsense_search_language: adsense_search_language
    adsense_search_logo: adsense_search_logo
    adsense_search_safe_mode: adsense_search_safe_mode
    adsense_search_textbox_length: adsense_search_textbox_length
destination:
  plugin: config
  config_name: adsense_oldcode.settings
